version: "3.3"
services:
  mariadb:
    image: mariadb
    container_name: wordpress-database
    restart: always
    volumes:
      - ../db/database.sql:/docker-entrypoint-initdb.d/database.sql
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: UX5O3gNNzWNtotuO9GX6EADeBpMtdzGd
    networks:
      - wp-network
  wordpress:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        WORDPRESS_VERSION: 4.9.4
    image: communica/wordpress:local-dev
    container_name: wordpress-application
    depends_on:
      - mariadb
    volumes:
      - ../.build/themes:/var/www/html/wp-content/themes
      - ../.build/plugins:/var/www/html/wp-content/plugins
      - ../.build/uploads:/var/www/html/wp-content/uploads
    ports:
      - "8000:80"
    links:
      - mariadb:mysql
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_PASSWORD: UX5O3gNNzWNtotuO9GX6EADeBpMtdzGd
      MYSQL_DATABASE: wordpress
      WORDPRESS_DEBUG: 1
    networks:
      - wp-network
networks:
    wp-network:
        driver: bridge
